name: Deploy Updated Client
on:
  workflow_dispatch: 
  # push:
  #   branches:
  #     - main

jobs:
  build-client:
    runs-on: build
    steps:
      - name: checkout
        uses: actions/checkout@v4
        
      - name: build client
        shell: pwsh
        run: |
          cd .\Scripts\
          .\Publish-Client.ps1

      - name: package artifact
        uses: actions/upload-artifact@v4
        with:
          name: ScanLab-Client
          path: Client/Publish/
  deploy-client:
    runs-on: sp500v2
    needs: build-client
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ScanLab-Client
          path: artifacts/
        
      - name: Publish Client
        shell: bash
        run: |
          unzip artifacts/ScanLab-Client.zip -d ~/Desktop/ScanLab/Client
