name: Deploy Updated Admin
on:
  workflow_dispatch: 
  # push:
  #   branches:
  #     - main
  #     - deploy-admin

jobs:
  deploy-admin:
    runs-on: self-hosted
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        
      - name: Publish Admin
        shell: pwsh
        run: |
          cd .\Scripts\
          .\Publish-Admin.ps1
          
      - name: Copy Published Admin & Update IIS target dir (symbolic link)
        shell: pwsh
        run: |
          $shortSha = $env:GITHUB_SHA.Substring(0, 7)
          $folderPath = "C:/ScanLab/Admin/$shortSha/"

          if (-not (Test-Path -PathType Container $folderPath)) {
              New-Item -Path $folderPath -ItemType Directory
          } else {
              Write-Host "Folder already exists!"
          }
          
          Copy-Item -Path "./Admin/Publish/windows/*" -Destination "$folderPath" -Recurse -Force
          Remove-Item -Path "C:/ScanLab/Admin/main/" -ErrorAction SilentlyContinue
          New-Item -ItemType SymbolicLink -Path "C:/ScanLab/Admin/main/" -Target "$folderPath"
          
  cleanup:
    runs-on: self-hosted
    needs: deploy-admin
    steps:
      - name: Clean folder
        shell: pwsh
        run: |
          Remove-Item -Recurse -Force ${{ github.workspace }}\*
